# Generated by Django 4.0.5 on 2022-07-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palatable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dietary',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
