# Generated by Django 4.0.5 on 2022-07-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palatable', '0003_explorer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explorer',
            name='diet',
            field=models.CharField(max_length=50),
        ),
    ]
