# Generated by Django 4.0.5 on 2022-07-16 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('palatable', '0004_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
