# Generated by Django 4.0.5 on 2022-07-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palatable', '0006_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favourites',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
