# Generated by Django 4.0.5 on 2022-07-17 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('palatable', '0007_user_favourites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='dietary',
            new_name='diet',
        ),
    ]
