# Generated by Django 4.0.5 on 2022-07-17 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('palatable', '0008_rename_dietary_user_diet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='diet',
            new_name='dietary',
        ),
    ]
