# Generated by Django 4.0.5 on 2022-07-29 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palatable', '0009_rename_diet_user_dietary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, unique=True)),
                ('recipe', models.CharField(max_length=1000000000)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='favourites',
            field=models.CharField(max_length=1000000000),
        ),
    ]
